import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/server'
import { normalizePhone } from '@/lib/utils/phone'

export async function GET(request: Request) {
  const supabase = createAdminClient()
  const { searchParams } = new URL(request.url)
  const status = searchParams.get('status')
  const date = searchParams.get('date')

  const clientId = searchParams.get('client_id')
  const dateFrom = searchParams.get('date_from')
  const dateTo = searchParams.get('date_to')
  const createdFrom = searchParams.get('created_from')  // ISO date — default 60-day window
  const tripType = searchParams.get('trip_type')
  const source = searchParams.get('source')
  const search = searchParams.get('search')
  const includeLegs = searchParams.get('include_legs') === '1'

  const selectFields = includeLegs
    ? '*, booking_legs(id, day_number, leg_date, leg_status), client:clients!client_id(id, name, primary_phone, primary_email, client_type, is_vip, is_verified, company:companies!company_id(id, name)), company:companies(id, name), driver:drivers(id, name, phone, vehicle_name, vehicle_number, vehicle_type, status)'
    : '*, client:clients!client_id(id, name, primary_phone, primary_email, client_type, is_vip, is_verified, company:companies!company_id(id, name)), company:companies(id, name), driver:drivers(id, name, phone, vehicle_name, vehicle_number, vehicle_type, status)'

  let query = supabase
    .from('bookings')
    .select(selectFields)
    .order('created_at', { ascending: false })
    .limit(500)

  if (status) query = query.eq('status', status)
  if (date) query = query.eq('pickup_date', date)
  if (clientId) query = query.or(`client_id.eq.${clientId},guest_client_id.eq.${clientId}`)
  if (dateFrom) query = query.gte('pickup_date', dateFrom)
  if (dateTo) query = query.lte('pickup_date', dateTo)
  if (createdFrom) query = query.gte('created_at', createdFrom)
  if (tripType) query = query.eq('trip_type', tripType)
  if (source) query = query.eq('source', source)
  if (search) query = query.ilike('booking_ref', `%${search}%`)

  const { data, error } = await query
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data)
}

export async function POST(request: Request) {
  const supabase = createAdminClient()
  const body = await request.json()
  if (body.guest_phone) body.guest_phone = normalizePhone(body.guest_phone)

  // booking_ref is generated by the DB function next_booking_ref() as the column default
  const { booking_ref: _unused, ...bodyWithoutRef } = body
  const flags: string[] = []
  if (!body.pickup_location) flags.push('missing_pickup')
  if (!body.pickup_date) flags.push('missing_date')
  if (!body.pickup_time) flags.push('missing_time')
  if (!body.company_id) flags.push('unknown_company')
  if (!body.drop_location) flags.push('missing_drop')
  if (body.guest_name && !body.client_id) flags.push('guest_booking')

  const { data, error } = await supabase
    .from('bookings')
    .insert({ ...bodyWithoutRef, flags, status: body.status || 'draft' })
    .select()
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  await supabase.from('booking_status_history').insert({
    booking_id: data.id,
    new_status: data.status,
    changed_by: 'system',
  })

  // Possible-duplicate detection: same client + same date, matching guest or location
  if (data.client_id && data.pickup_date) {
    const { data: sameDay } = await supabase
      .from('bookings')
      .select('id, flags, guest_name, pickup_location')
      .eq('client_id', data.client_id)
      .eq('pickup_date', data.pickup_date)
      .not('status', 'in', '("cancelled","completed")')
      .neq('id', data.id)

    const guestFirst = (data.guest_name as string | null)?.toLowerCase().split(' ')[0] ?? ''
    const locFirst   = (data.pickup_location as string | null)?.toLowerCase().split(' ').slice(0, 3).join(' ') ?? ''

    const matches = (sameDay ?? []).filter(s => {
      if (guestFirst && s.guest_name?.toLowerCase().includes(guestFirst)) return true
      if (locFirst   && s.pickup_location?.toLowerCase().includes(locFirst)) return true
      return false
    })

    if (matches.length > 0) {
      // Flag the new booking
      await supabase.from('bookings')
        .update({ flags: [...(data.flags as string[] || []), 'possible_duplicate'] })
        .eq('id', data.id)
      // Flag existing similar bookings that aren't already flagged
      for (const m of matches) {
        const mFlags = (m.flags as string[] | null) ?? []
        if (!mFlags.includes('possible_duplicate')) {
          await supabase.from('bookings')
            .update({ flags: [...mFlags, 'possible_duplicate'] })
            .eq('id', m.id)
        }
      }
    }
  }

  return NextResponse.json(data, { status: 201 })
}
